name: uberapp
description: "A new Flutter project."
publish_to: 
version: 1.0.0+1
environment:
  sdk: '>=3.2.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  sizer: ^2.0.15
  cupertino_icons: ^1.0.2
  country_picker: ^2.0.25
  font_awesome_flutter: ^10.7.0
  pin_code_fields: ^8.0.1
  persistent_bottom_nav_bar: ^5.0.2
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/categories/
    
  fonts:
    - family: UberMoveMedium
      fonts:
        - asset: assets/fonts/UberMoveMedium.otf
    - family: UberMoveBold
      fonts:
        - asset: assets/fonts/UberMoveBold.otf